### ISSUE TITLE
Quantify resources for TP* and schedule tests

### ISSUE THREAD

**Issue by cgizzi** [rhea-group/hn-prototype-platform#12]
Characterise (estimate) the minimum and maximum testing ICT resources we need during TP1, TP2, TP3 and TP4 for discussion with BG (27thApril) and allocate tests on Sprints

**Comment by tkotisis** [comment]
Estimates for test resources are based on data available in test case descriptions.

**Comment by tkotisis** [comment]
As clarified today (20170427) in the meeting with the buyers group, we are not expected to run all test cases.
