### ISSUE TITLE
create and configure an account on readthedocs.org 

### ISSUE THREAD

**Issue by loomis** [rhea-group/hn-prototype-platform#7]
- [x] create an account on readthedocs.org for this organization
 - [x] configure the account to build the contained documentation automatically

**Comment by loomis** [comment]
The account has been created on ReadTheDocs.org.  The username is "hnscicloud-rhea".  The password has been communicated to Rhea personnel.

The automated build of the documentation for ReadTheDocs.org is waiting on the owners to approve access to the GitHub repository by the ReadTheDocs website.

**Comment by cgizzi** [comment]
Access has been approved

**Comment by loomis** [comment]
I do not have sufficient privileges on the repository to activate the web hook.  Someone from Rhea will have to do this.  Splitting that task from this ticket.

**Comment by loomis** [comment]
The documentation is visible here: http://hnscicloud-rhea.readthedocs.io/en/latest/.
